"""Review Pack Importer -- reads reviewed Excel, applies feedback via backend.

Reads Excel review packs generated by generate_review_pack.py, parses
Rob's feedback (PL/EN bilingual), and executes via rfp_feedback.py backend.

Usage:
  python src/import_review_pack.py path/to/PACK.xlsx --dry-run
  python src/import_review_pack.py path/to/PACK.xlsx --apply
  python src/import_review_pack.py path/to/PACK.xlsx --apply --force
"""

import argparse
import hashlib
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    from dotenv import load_dotenv
    load_dotenv(override=False)
except ImportError:
    pass

PROJECT_ROOT = Path(__file__).resolve().parents[1]
KB_DIR = PROJECT_ROOT / "data" / "kb"
VERIFIED_DIR = KB_DIR / "verified"
DRAFTS_DIR = KB_DIR / "drafts"
PROFILES_DIR = PROJECT_ROOT / "config" / "product_profiles" / "_effective"
PROCESSED_PACKS = KB_DIR / "processed_packs.jsonl"
GENERAL_FEEDBACK_QUEUE = KB_DIR / "general_feedback_queue.jsonl"


# ---------------------------------------------------------------------------
# Bilingual feedback parsing
# ---------------------------------------------------------------------------

FEEDBACK_PATTERNS = {
    # Polish
    "brakuje": "add_detail",
    "zle": "reject", "nieprawda": "reject", "nieaktualne": "reject",
    "dotyczy": "retag", "popraw": "update", "dodaj": "add_detail",
    "usun": "remove_detail",
    # English
    "missing": "add_detail", "wrong": "reject", "outdated": "reject",
    "incorrect": "reject", "add": "add_detail", "remove": "remove_detail",
    "should mention": "add_detail", "applies to": "retag",
    "ok": "approve", "good": "approve", "correct": "approve",
    "dobrze": "approve", "ok": "approve",
}

# Map parsed intent to import action
INTENT_TO_ACTION = {
    "approve": "APPROVE",
    "reject": "REJECT",
    "update": "UPDATE",
    "add_detail": "UPDATE",
    "remove_detail": "UPDATE",
    "retag": "UPDATE",
}


def parse_feedback_rules(feedback: str) -> Optional[str]:
    """Parse feedback text using bilingual keyword lexicon.

    Returns intent string or None if no match.
    """
    if not feedback or not feedback.strip():
        return None
    text = feedback.lower().strip()
    for pattern, intent in FEEDBACK_PATTERNS.items():
        if pattern in text:
            return intent
    return None


def parse_feedback_llm(feedback: str, question: str,
                       model: str = "gemini-flash") -> str:
    """LLM fallback for feedback parsing."""
    from kb_extract_historical import call_llm

    prompt = f"""Parse this RFP review feedback into an action.

QUESTION: {question}
FEEDBACK (may be in Polish or English): {feedback}

Return EXACTLY one word: APPROVE, UPDATE, REJECT, or SKIP
"""
    raw = call_llm(prompt, model=model)
    result = raw.strip().upper()
    if result in ("APPROVE", "UPDATE", "REJECT", "SKIP"):
        return result
    return "SKIP"


# ---------------------------------------------------------------------------
# Stale detection
# ---------------------------------------------------------------------------

def _content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def check_stale(entry_ids: list[str], revision_hash: str) -> bool:
    """Check if any referenced entry has changed since pack generation.

    Returns True if stale (hash mismatch).
    """
    if not revision_hash or not entry_ids:
        return False

    from rfp_feedback import find_entry, load_entry

    for eid in entry_ids:
        path = find_entry(eid)
        if path:
            entry = load_entry(path)
            current_hash = _content_hash(entry.get("answer", ""))
            if current_hash != revision_hash:
                return True
    return False


# ---------------------------------------------------------------------------
# Pack tracking
# ---------------------------------------------------------------------------

def is_already_processed(pack_id: str) -> bool:
    """Check if pack_id has been processed before."""
    if not PROCESSED_PACKS.exists():
        return False
    for line in PROCESSED_PACKS.read_text(encoding="utf-8").strip().split("\n"):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
            if record.get("pack_id") == pack_id:
                return True
        except json.JSONDecodeError:
            continue
    return False


def mark_processed(pack_id: str, file_path: str, summary: dict) -> None:
    """Record pack as processed."""
    PROCESSED_PACKS.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "pack_id": pack_id,
        "file": file_path,
        "processed_at": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "summary": summary,
    }
    with open(PROCESSED_PACKS, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Excel reading
# ---------------------------------------------------------------------------

REQUIRED_HEADERS = ["Question", "Answer", "Action"]


def validate_excel(path: Path) -> tuple[bool, str, dict]:
    """Validate Excel structure. Returns (ok, error_msg, metadata)."""
    from openpyxl import load_workbook

    try:
        wb = load_workbook(str(path), read_only=True, data_only=True)
    except Exception as e:
        return False, f"Cannot open Excel: {e}", {}

    # Check sheets
    if "Questions & Answers" not in wb.sheetnames:
        return False, "Missing sheet 'Questions & Answers'", {}

    # Read metadata
    metadata = {}
    if "_metadata" in wb.sheetnames:
        ws_meta = wb["_metadata"]
        for row in ws_meta.iter_rows(min_row=1, max_col=2, values_only=True):
            if row[0] and row[1]:
                metadata[str(row[0])] = str(row[1])

    # Check headers
    ws = wb["Questions & Answers"]
    header_row = [cell.value for cell in next(ws.iter_rows(min_row=1, max_row=1))]
    for required in REQUIRED_HEADERS:
        if required not in header_row:
            return False, f"Missing column '{required}'", metadata

    wb.close()
    return True, "", metadata


def parse_rows(path: Path) -> list[dict]:
    """Parse all data rows from the Excel pack."""
    from openpyxl import load_workbook

    wb = load_workbook(str(path), read_only=True, data_only=True)
    ws = wb["Questions & Answers"]

    # Build column index from header
    header_row = [cell.value for cell in next(ws.iter_rows(min_row=1, max_row=1))]
    col_map = {name: idx for idx, name in enumerate(header_row) if name}

    rows = []
    for row_num, row in enumerate(ws.iter_rows(min_row=2, values_only=True), 2):
        def get(col_name):
            idx = col_map.get(col_name)
            if idx is not None and idx < len(row):
                return row[idx]
            return None

        action = str(get("Action") or "").strip().upper()
        if not action or action == "SKIP":
            rows.append({"row": row_num, "action": "SKIP", "skipped": True})
            continue

        entry_ids = []
        entry_ids_json = get("_entry_ids_json")
        if entry_ids_json:
            try:
                entry_ids = json.loads(str(entry_ids_json))
            except (json.JSONDecodeError, TypeError):
                pass

        if not entry_ids:
            # Fallback: parse from "KB Entries Used" column
            kb_used = str(get("KB Entries Used") or "")
            if kb_used:
                entry_ids = [e.strip() for e in kb_used.split(",") if e.strip()]

        rows.append({
            "row": row_num,
            "question": str(get("Question") or ""),
            "topic": str(get("Topic") or ""),
            "category": str(get("Category") or "technical"),
            "answer": str(get("Answer") or ""),
            "entry_ids": entry_ids,
            "confidence": float(get("Confidence") or 0),
            "action": action,
            "feedback": str(get("Feedback") or ""),
            "robs_answer": str(get("Rob's Answer") or ""),
            "revision_hash": str(get("_revision_hash") or ""),
            "skipped": False,
        })

    wb.close()
    return rows


def parse_general_feedback(path: Path) -> list[dict]:
    """Parse general feedback sheet."""
    from openpyxl import load_workbook

    wb = load_workbook(str(path), read_only=True, data_only=True)
    if "General Feedback" not in wb.sheetnames:
        wb.close()
        return []

    ws = wb["General Feedback"]
    items = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if len(row) >= 2 and row[1]:
            text = str(row[1]).strip()
            # Skip placeholder text
            if text.startswith("(") and text.endswith(")"):
                continue
            if not text:
                continue
            scope = str(row[2]).strip() if len(row) > 2 and row[2] else "general"
            items.append({"feedback": text, "scope": scope})

    wb.close()
    return items


# ---------------------------------------------------------------------------
# Execution engine
# ---------------------------------------------------------------------------

def execute_row(row: dict, family: str, dry_run: bool = True,
                model: str = "gemini-flash") -> dict:
    """Execute one row's action via the rfp_feedback.py backend.

    Returns result dict with status and details.
    """
    from rfp_feedback import (
        cmd_approve, cmd_reject, cmd_correct_offline, cmd_correct,
        check_forbidden_claims, load_profile, find_entry, load_entry,
        save_entry, append_feedback_log, find_entry_dir,
    )

    action = row["action"]
    entry_ids = row.get("entry_ids", [])
    feedback = row.get("feedback", "")
    robs_answer = row.get("robs_answer", "")
    revision_hash = row.get("revision_hash", "")

    result = {
        "row": row["row"],
        "action": action,
        "status": "pending",
        "detail": "",
    }

    # Stale detection
    if entry_ids and revision_hash:
        if check_stale(entry_ids, revision_hash):
            result["status"] = "CONFLICT"
            result["detail"] = "Entry changed since pack was generated"
            return result

    # Determine answer text to validate
    answer_text = robs_answer if robs_answer else row.get("answer", "")

    # Profile validation for APPROVE and UPDATE
    if action in ("APPROVE", "UPDATE", "NEW"):
        profile = load_profile(family)
        if answer_text:
            violations = check_forbidden_claims(answer_text, profile)
            if violations:
                result["status"] = "QUARANTINED"
                result["detail"] = f"Forbidden claim: {violations[0]}"
                return result

    if dry_run:
        result["status"] = f"WOULD_{action}"
        return result

    # Execute
    if action == "APPROVE":
        if not entry_ids:
            result["status"] = "SKIPPED"
            result["detail"] = "No entry IDs to approve"
            return result
        for eid in entry_ids:
            path, dir_type = find_entry_dir(eid)
            if path and dir_type == "drafts":
                ret = cmd_approve(eid)
                if ret == 0:
                    result["status"] = "APPROVED"
                    result["detail"] = f"Approved {eid}"
                else:
                    result["status"] = "ERROR"
                    result["detail"] = f"Failed to approve {eid}"
                break
        else:
            # Entry exists but not in drafts — just mark as ok
            result["status"] = "APPROVED"
            result["detail"] = "Already verified"

    elif action == "UPDATE":
        if not entry_ids:
            result["status"] = "SKIPPED"
            result["detail"] = "No entry IDs to update"
            return result
        eid = entry_ids[0]
        if robs_answer:
            ret = cmd_correct_offline(eid, robs_answer, dry_run=False)
            result["parse_method"] = "direct"
        else:
            correction = feedback or "Update per review feedback"
            ret = cmd_correct(eid, correction, dry_run=False, model=model)
            result["parse_method"] = "llm"
        result["status"] = "UPDATED" if ret == 0 else "ERROR"
        result["detail"] = f"Updated {eid}"

    elif action == "REJECT":
        if not entry_ids:
            result["status"] = "SKIPPED"
            result["detail"] = "No entry IDs to reject"
            return result
        eid = entry_ids[0]
        reason = feedback or "Rejected via review pack"
        path, dir_type = find_entry_dir(eid)
        if path and dir_type == "drafts":
            ret = cmd_reject(eid, reason)
            result["status"] = "REJECTED" if ret == 0 else "ERROR"
            result["detail"] = f"Rejected {eid}: {reason[:60]}"
        else:
            result["status"] = "SKIPPED"
            result["detail"] = f"{eid} not in drafts"

    elif action == "NEW":
        answer = robs_answer or row.get("answer", "")
        if not answer or answer == "No answer found in KB":
            result["status"] = "SKIPPED"
            result["detail"] = "No answer text for new entry"
            return result

        # Create draft entry
        draft = _create_draft(
            question=row["question"],
            answer=answer,
            family=family,
            category=row.get("category", "technical"),
            topic=row.get("topic", ""),
            feedback=feedback,
        )
        result["status"] = "CREATED"
        result["detail"] = f"Created {draft['id']}"

    else:
        result["status"] = "SKIPPED"
        result["detail"] = f"Unknown action: {action}"

    return result


def _create_draft(question: str, answer: str, family: str,
                  category: str = "technical", topic: str = "",
                  feedback: str = "") -> dict:
    """Create a new draft entry from review pack feedback."""
    from rfp_feedback import save_entry, append_feedback_log

    # Find next draft ID
    family_dir = DRAFTS_DIR / family
    family_dir.mkdir(parents=True, exist_ok=True)
    existing = list(family_dir.glob("KB_DRAFT_*.json"))
    max_id = 0
    for f in existing:
        m = re.search(r'KB_DRAFT_(\d+)', f.stem)
        if m:
            max_id = max(max_id, int(m.group(1)))
    next_id = max_id + 1

    entry_id = f"KB_DRAFT_{next_id:04d}"
    now_iso = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    today = datetime.now().strftime("%Y-%m-%d")

    entry = {
        "id": entry_id,
        "question": question,
        "answer": answer,
        "question_variants": [],
        "solution_codes": [],
        "family_code": family,
        "category": category,
        "subcategory": topic,
        "tags": [],
        "confidence": "draft",
        "source_rfps": [],
        "last_updated": today,
        "cloud_native_only": False,
        "notes": f"Created from review pack. Feedback: {feedback[:200]}",
        "generated_by": "import_review_pack.py",
        "generated_at": now_iso,
        "feedback_history": [{
            "action": "created_from_review_pack",
            "timestamp": now_iso,
        }],
    }

    path = family_dir / f"{entry_id}.json"
    save_entry(entry, path)

    append_feedback_log({
        "action": "new_from_review_pack",
        "entry_id": entry_id,
        "family": family,
        "question": question[:80],
    })

    return entry


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def import_pack(excel_path: Path, dry_run: bool = True,
                force: bool = False,
                model: str = "gemini-flash") -> dict:
    """Full import pipeline. Returns summary dict."""
    summary = {
        "approved": 0, "updated": 0, "rejected": 0, "new": 0,
        "skipped": 0, "conflicts": 0, "quarantined": 0, "errors": 0,
        "total": 0, "actionable": 0,
        "update_rule_parsed": 0, "update_llm_parsed": 0,
        "general_feedback": 0,
    }

    # Step 1: Validate
    print(f"[Step 1] Validating {excel_path.name}...")
    ok, error, metadata = validate_excel(excel_path)
    if not ok:
        print(f"[ERROR] {error}")
        return summary

    pack_id = metadata.get("pack_id", excel_path.stem)
    family = metadata.get("family", "unknown")
    print(f"  Pack: {pack_id}, Family: {family}")

    if not force and is_already_processed(pack_id):
        print(f"[ERROR] Pack {pack_id} already processed. Use --force to re-import.")
        return summary

    # Step 2: Parse rows
    print(f"[Step 2] Parsing rows...")
    rows = parse_rows(excel_path)
    summary["total"] = len(rows)
    actionable = [r for r in rows if not r.get("skipped")]
    summary["actionable"] = len(actionable)
    print(f"  Total: {len(rows)}, Actionable: {len(actionable)}")

    # Step 3-6: Execute each row
    print(f"[Step 3-6] {'Previewing' if dry_run else 'Executing'} actions...")
    results = []
    for row in rows:
        if row.get("skipped"):
            summary["skipped"] += 1
            results.append({"row": row["row"], "action": "SKIP", "status": "SKIPPED"})
            continue

        # Step 4: Parse feedback if action seems underspecified
        if row["action"] in ("UPDATE",) and row.get("feedback"):
            intent = parse_feedback_rules(row["feedback"])
            if intent:
                mapped = INTENT_TO_ACTION.get(intent, row["action"])
                if mapped != row["action"]:
                    row["action"] = mapped

        result = execute_row(row, family, dry_run=dry_run, model=model)
        results.append(result)

        status = result["status"]
        if status in ("APPROVED", "WOULD_APPROVE"):
            summary["approved"] += 1
        elif status in ("UPDATED", "WOULD_UPDATE"):
            summary["updated"] += 1
            if result.get("parse_method") == "direct":
                summary["update_rule_parsed"] += 1
            else:
                summary["update_llm_parsed"] += 1
        elif status in ("REJECTED", "WOULD_REJECT"):
            summary["rejected"] += 1
        elif status in ("CREATED", "WOULD_NEW"):
            summary["new"] += 1
        elif status == "CONFLICT":
            summary["conflicts"] += 1
        elif status == "QUARANTINED":
            summary["quarantined"] += 1
        elif status == "ERROR":
            summary["errors"] += 1
        else:
            summary["skipped"] += 1

    # Step 7: General feedback
    print(f"[Step 7] Processing general feedback...")
    general = parse_general_feedback(excel_path)
    if general and not dry_run:
        GENERAL_FEEDBACK_QUEUE.parent.mkdir(parents=True, exist_ok=True)
        with open(GENERAL_FEEDBACK_QUEUE, "a", encoding="utf-8") as f:
            for item in general:
                item["pack_id"] = pack_id
                item["family"] = family
                item["timestamp"] = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
                f.write(json.dumps(item, ensure_ascii=False) + "\n")
    summary["general_feedback"] = len(general)
    if general:
        print(f"  {len(general)} ticket(s) {'queued' if not dry_run else 'found'}")

    # Step 8: Report + track
    print_import_report(pack_id, family, summary, results, dry_run)

    if not dry_run:
        mark_processed(pack_id, str(excel_path), summary)
        print(f"  Pack marked as processed.")

    return summary


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def print_import_report(pack_id: str, family: str, summary: dict,
                        results: list[dict], dry_run: bool) -> None:
    """Print formatted import report."""
    mode = "DRY RUN" if dry_run else "APPLIED"
    border = "=" * 60

    print(f"\n{border}")
    print(f"  Review Pack Import Report [{mode}]")
    print(f"{border}")
    print(f"  Pack: {pack_id} | Family: {family}")
    print(f"  Rows: {summary['total']} total, "
          f"{summary['actionable']} actionable")
    print()
    print(f"  APPROVED:     {summary['approved']:>3}")

    update_detail = ""
    if summary["updated"]:
        parts = []
        if summary["update_rule_parsed"]:
            parts.append(f"{summary['update_rule_parsed']} direct")
        if summary["update_llm_parsed"]:
            parts.append(f"{summary['update_llm_parsed']} LLM-parsed")
        if parts:
            update_detail = f" ({', '.join(parts)})"
    print(f"  UPDATED:      {summary['updated']:>3}{update_detail}")

    print(f"  REJECTED:     {summary['rejected']:>3}")
    print(f"  NEW:          {summary['new']:>3}")
    print(f"  SKIPPED:      {summary['skipped']:>3}")
    if summary["conflicts"]:
        print(f"  CONFLICTS:    {summary['conflicts']:>3} (stale entries)")
    if summary["quarantined"]:
        print(f"  QUARANTINED:  {summary['quarantined']:>3} (forbidden claim violation)")
    if summary["errors"]:
        print(f"  ERRORS:       {summary['errors']:>3}")
    if summary["general_feedback"]:
        print(f"\n  General Feedback: {summary['general_feedback']} ticket(s) "
              f"{'queued' if not dry_run else 'found'}")
    print(f"{border}")

    # Detail per non-skip result
    details = [r for r in results if r.get("status") not in ("SKIPPED", None)]
    if details:
        print(f"\n  Details:")
        for r in details[:20]:
            print(f"    Row {r.get('row', '?')}: {r.get('action', '?')} -> "
                  f"{r.get('status', '?')} {r.get('detail', '')[:50]}")
        if len(details) > 20:
            print(f"    ... and {len(details) - 20} more")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Import Review Pack -- apply Excel feedback to KB",
    )
    parser.add_argument("excel", type=str, help="Path to review pack .xlsx")
    parser.add_argument("--dry-run", action="store_true", default=True,
                        help="Preview changes (default)")
    parser.add_argument("--apply", action="store_true",
                        help="Actually apply changes")
    parser.add_argument("--force", action="store_true",
                        help="Allow re-import of processed pack")
    parser.add_argument("--model", default="gemini-flash",
                        help="LLM model for feedback parsing (default: gemini-flash)")
    args = parser.parse_args()

    excel_path = Path(args.excel)
    if not excel_path.exists():
        print(f"[ERROR] File not found: {excel_path}")
        return 1

    dry_run = not args.apply
    import_pack(excel_path, dry_run=dry_run, force=args.force, model=args.model)
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
